/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from '@payloadcms/db-postgres'
import {
  pgTable,
  index,
  uniqueIndex,
  foreignKey,
  integer,
  varchar,
  timestamp,
  serial,
  numeric,
  jsonb,
  text,
  boolean,
  pgEnum,
} from '@payloadcms/db-postgres/drizzle/pg-core'
import { sql, relations } from '@payloadcms/db-postgres/drizzle'
export const enum_categories_marketing_content_quick_specs_icon = pgEnum(
  'enum_categories_marketing_content_quick_specs_icon',
  [
    'building-2',
    'package',
    'shopping-bag',
    'wifi',
    'shield',
    'users',
    'truck',
    'zap',
    'store',
    'map-pin',
    'tag',
    'lock',
    'camera',
    'star',
    'check',
  ],
)
export const enum_units_status = pgEnum('enum_units_status', ['available', 'under-offer', 'leased'])
export const enum_units_lease_type = pgEnum('enum_units_lease_type', [
  'nnn',
  'full-service',
  'modified-gross',
])
export const enum_units_building = pgEnum('enum_units_building', [
  'building-a',
  'building-b',
  'annex',
])
export const enum_pages_blocks_cowork_hero_amenities_icon = pgEnum(
  'enum_pages_blocks_cowork_hero_amenities_icon',
  ['wifi', 'coffee', 'users', 'shield', 'clock', 'building'],
)
export const enum_pages_status = pgEnum('enum_pages_status', ['draft', 'published'])
export const enum__pages_v_blocks_cowork_hero_amenities_icon = pgEnum(
  'enum__pages_v_blocks_cowork_hero_amenities_icon',
  ['wifi', 'coffee', 'users', 'shield', 'clock', 'building'],
)
export const enum__pages_v_version_status = pgEnum('enum__pages_v_version_status', [
  'draft',
  'published',
])
export const enum_leads_interest = pgEnum('enum_leads_interest', [
  'office',
  'warehouse',
  'retail',
  'self-storage',
  'coworking',
  'restaurant',
  'residential',
])
export const enum_leads_form_type = pgEnum('enum_leads_form_type', ['contact-form', 'book-a-tour'])
export const enum_leads_status = pgEnum('enum_leads_status', ['new', 'contacted', 'closed'])
export const enum_posts_category_tag = pgEnum('enum_posts_category_tag', [
  'news',
  'leasing',
  'community',
  'insights',
])

export const users_sessions = pgTable(
  'users_sessions',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }),
    expiresAt: timestamp('expires_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }).notNull(),
  },
  (columns) => [
    index('users_sessions_order_idx').on(columns._order),
    index('users_sessions_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [users.id],
      name: 'users_sessions_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const users = pgTable(
  'users',
  {
    id: serial('id').primaryKey(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    email: varchar('email').notNull(),
    resetPasswordToken: varchar('reset_password_token'),
    resetPasswordExpiration: timestamp('reset_password_expiration', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar('salt'),
    hash: varchar('hash'),
    loginAttempts: numeric('login_attempts', { mode: 'number' }).default(0),
    lockUntil: timestamp('lock_until', { mode: 'string', withTimezone: true, precision: 3 }),
  },
  (columns) => [
    index('users_updated_at_idx').on(columns.updatedAt),
    index('users_created_at_idx').on(columns.createdAt),
    uniqueIndex('users_email_idx').on(columns.email),
  ],
)

export const media = pgTable(
  'media',
  {
    id: serial('id').primaryKey(),
    alt: varchar('alt').notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    url: varchar('url'),
    thumbnailURL: varchar('thumbnail_u_r_l'),
    filename: varchar('filename'),
    mimeType: varchar('mime_type'),
    filesize: numeric('filesize', { mode: 'number' }),
    width: numeric('width', { mode: 'number' }),
    height: numeric('height', { mode: 'number' }),
    focalX: numeric('focal_x', { mode: 'number' }),
    focalY: numeric('focal_y', { mode: 'number' }),
  },
  (columns) => [
    index('media_updated_at_idx').on(columns.updatedAt),
    index('media_created_at_idx').on(columns.createdAt),
    uniqueIndex('media_filename_idx').on(columns.filename),
  ],
)

export const categories_marketing_content_quick_specs = pgTable(
  'categories_marketing_content_quick_specs',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    icon: enum_categories_marketing_content_quick_specs_icon('icon').notNull(),
    title: varchar('title').notNull(),
    subtitle: varchar('subtitle'),
  },
  (columns) => [
    index('categories_marketing_content_quick_specs_order_idx').on(columns._order),
    index('categories_marketing_content_quick_specs_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [categories.id],
      name: 'categories_marketing_content_quick_specs_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const categories = pgTable(
  'categories',
  {
    id: serial('id').primaryKey(),
    name: varchar('name').notNull(),
    slug: varchar('slug').notNull(),
    description: varchar('description'),
    heroTitle: varchar('hero_title'),
    heroDescription: varchar('hero_description'),
    heroBackgroundImage: integer('hero_background_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    marketingContent_heroTitle: varchar('marketing_content_hero_title'),
    marketingContent_heroSubheadline: varchar('marketing_content_hero_subheadline'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('categories_slug_idx').on(columns.slug),
    index('categories_hero_background_image_idx').on(columns.heroBackgroundImage),
    index('categories_updated_at_idx').on(columns.updatedAt),
    index('categories_created_at_idx').on(columns.createdAt),
  ],
)

export const units_features = pgTable(
  'units_features',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    feature: varchar('feature'),
  },
  (columns) => [
    index('units_features_order_idx').on(columns._order),
    index('units_features_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [units.id],
      name: 'units_features_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const units = pgTable(
  'units',
  {
    id: serial('id').primaryKey(),
    unitNumber: varchar('unit_number').notNull(),
    type: integer('type_id')
      .notNull()
      .references(() => categories.id, {
        onDelete: 'set null',
      }),
    status: enum_units_status('status').notNull().default('available'),
    leaseType: enum_units_lease_type('lease_type').notNull(),
    building: enum_units_building('building').notNull(),
    sqFt: numeric('sq_ft', { mode: 'number' }).notNull(),
    price_amount: numeric('price_amount', { mode: 'number' }).notNull(),
    floorPlan: integer('floor_plan_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    description: jsonb('description'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('units_type_idx').on(columns.type),
    index('units_floor_plan_idx').on(columns.floorPlan),
    index('units_updated_at_idx').on(columns.updatedAt),
    index('units_created_at_idx').on(columns.createdAt),
  ],
)

export const units_rels = pgTable(
  'units_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    mediaID: integer('media_id'),
  },
  (columns) => [
    index('units_rels_order_idx').on(columns.order),
    index('units_rels_parent_idx').on(columns.parent),
    index('units_rels_path_idx').on(columns.path),
    index('units_rels_media_id_idx').on(columns.mediaID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [units.id],
      name: 'units_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['mediaID']],
      foreignColumns: [media.id],
      name: 'units_rels_media_fk',
    }).onDelete('cascade'),
  ],
)

export const directory = pgTable(
  'directory',
  {
    id: serial('id').primaryKey(),
    shopName: varchar('shop_name').notNull(),
    logo: integer('logo_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    unit: integer('unit_id')
      .notNull()
      .references(() => units.id, {
        onDelete: 'set null',
      }),
    category: integer('category_id').references(() => categories.id, {
      onDelete: 'set null',
    }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('directory_logo_idx').on(columns.logo),
    index('directory_unit_idx').on(columns.unit),
    index('directory_category_idx').on(columns.category),
    index('directory_updated_at_idx').on(columns.updatedAt),
    index('directory_created_at_idx').on(columns.createdAt),
  ],
)

export const pages_blocks_hero = pgTable(
  'pages_blocks_hero',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    title: varchar('title'),
    subtitle: varchar('subtitle'),
    image: integer('image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('pages_blocks_hero_order_idx').on(columns._order),
    index('pages_blocks_hero_parent_id_idx').on(columns._parentID),
    index('pages_blocks_hero_path_idx').on(columns._path),
    index('pages_blocks_hero_image_idx').on(columns.image),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [pages.id],
      name: 'pages_blocks_hero_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const pages_blocks_inventory_grid = pgTable(
  'pages_blocks_inventory_grid',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    title: varchar('title'),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('pages_blocks_inventory_grid_order_idx').on(columns._order),
    index('pages_blocks_inventory_grid_parent_id_idx').on(columns._parentID),
    index('pages_blocks_inventory_grid_path_idx').on(columns._path),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [pages.id],
      name: 'pages_blocks_inventory_grid_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const pages_blocks_content = pgTable(
  'pages_blocks_content',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    richText: jsonb('rich_text'),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('pages_blocks_content_order_idx').on(columns._order),
    index('pages_blocks_content_parent_id_idx').on(columns._parentID),
    index('pages_blocks_content_path_idx').on(columns._path),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [pages.id],
      name: 'pages_blocks_content_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const pages_blocks_cowork_hero_amenities = pgTable(
  'pages_blocks_cowork_hero_amenities',
  {
    _order: integer('_order').notNull(),
    _parentID: varchar('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    icon: enum_pages_blocks_cowork_hero_amenities_icon('icon'),
    label: varchar('label'),
  },
  (columns) => [
    index('pages_blocks_cowork_hero_amenities_order_idx').on(columns._order),
    index('pages_blocks_cowork_hero_amenities_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [pages_blocks_cowork_hero.id],
      name: 'pages_blocks_cowork_hero_amenities_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const pages_blocks_cowork_hero = pgTable(
  'pages_blocks_cowork_hero',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    overTitle: varchar('over_title'),
    title: varchar('title'),
    description: varchar('description'),
    backgroundImage: integer('background_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('pages_blocks_cowork_hero_order_idx').on(columns._order),
    index('pages_blocks_cowork_hero_parent_id_idx').on(columns._parentID),
    index('pages_blocks_cowork_hero_path_idx').on(columns._path),
    index('pages_blocks_cowork_hero_background_image_idx').on(columns.backgroundImage),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [pages.id],
      name: 'pages_blocks_cowork_hero_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const pages_blocks_pricing_cards_plans_features = pgTable(
  'pages_blocks_pricing_cards_plans_features',
  {
    _order: integer('_order').notNull(),
    _parentID: varchar('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    feature: varchar('feature'),
  },
  (columns) => [
    index('pages_blocks_pricing_cards_plans_features_order_idx').on(columns._order),
    index('pages_blocks_pricing_cards_plans_features_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [pages_blocks_pricing_cards_plans.id],
      name: 'pages_blocks_pricing_cards_plans_features_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const pages_blocks_pricing_cards_plans = pgTable(
  'pages_blocks_pricing_cards_plans',
  {
    _order: integer('_order').notNull(),
    _parentID: varchar('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    name: varchar('name'),
    price: numeric('price', { mode: 'number' }),
    frequency: varchar('frequency').default('/month'),
    isFeatured: boolean('is_featured').default(false),
  },
  (columns) => [
    index('pages_blocks_pricing_cards_plans_order_idx').on(columns._order),
    index('pages_blocks_pricing_cards_plans_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [pages_blocks_pricing_cards.id],
      name: 'pages_blocks_pricing_cards_plans_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const pages_blocks_pricing_cards = pgTable(
  'pages_blocks_pricing_cards',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    overTitle: varchar('over_title'),
    title: varchar('title'),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('pages_blocks_pricing_cards_order_idx').on(columns._order),
    index('pages_blocks_pricing_cards_parent_id_idx').on(columns._parentID),
    index('pages_blocks_pricing_cards_path_idx').on(columns._path),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [pages.id],
      name: 'pages_blocks_pricing_cards_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const pages_blocks_split_lead_section = pgTable(
  'pages_blocks_split_lead_section',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    image: integer('image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    overTitle: varchar('over_title'),
    title: varchar('title'),
    description: varchar('description'),
    formTitle: varchar('form_title').default('Request Information'),
    formDescription: varchar('form_description').default(
      'Tell us what you need and our leasing team will contact you shortly.',
    ),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('pages_blocks_split_lead_section_order_idx').on(columns._order),
    index('pages_blocks_split_lead_section_parent_id_idx').on(columns._parentID),
    index('pages_blocks_split_lead_section_path_idx').on(columns._path),
    index('pages_blocks_split_lead_section_image_idx').on(columns.image),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [pages.id],
      name: 'pages_blocks_split_lead_section_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const pages_blocks_home_hero = pgTable(
  'pages_blocks_home_hero',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    announcementText: varchar('announcement_text').default('Now Leasing'),
    title: varchar('title'),
    subtitle: varchar('subtitle'),
    backgroundImage: integer('background_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    primaryButtonLabel: varchar('primary_button_label').default('VIEW AVAILABLE SPACES'),
    primaryButtonHref: varchar('primary_button_href').default('/leasing'),
    secondaryButtonLabel: varchar('secondary_button_label').default('OUR STORY'),
    secondaryButtonHref: varchar('secondary_button_href').default('/home'),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('pages_blocks_home_hero_order_idx').on(columns._order),
    index('pages_blocks_home_hero_parent_id_idx').on(columns._parentID),
    index('pages_blocks_home_hero_path_idx').on(columns._path),
    index('pages_blocks_home_hero_background_image_idx').on(columns.backgroundImage),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [pages.id],
      name: 'pages_blocks_home_hero_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const pages_blocks_services_grid_items = pgTable(
  'pages_blocks_services_grid_items',
  {
    _order: integer('_order').notNull(),
    _parentID: varchar('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    title: varchar('title'),
    image: integer('image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    href: varchar('href'),
  },
  (columns) => [
    index('pages_blocks_services_grid_items_order_idx').on(columns._order),
    index('pages_blocks_services_grid_items_parent_id_idx').on(columns._parentID),
    index('pages_blocks_services_grid_items_image_idx').on(columns.image),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [pages_blocks_services_grid.id],
      name: 'pages_blocks_services_grid_items_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const pages_blocks_services_grid = pgTable(
  'pages_blocks_services_grid',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    title: varchar('title').default('Everything You Need, All in One Place'),
    description: varchar('description'),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('pages_blocks_services_grid_order_idx').on(columns._order),
    index('pages_blocks_services_grid_parent_id_idx').on(columns._parentID),
    index('pages_blocks_services_grid_path_idx').on(columns._path),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [pages.id],
      name: 'pages_blocks_services_grid_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const pages_blocks_featured_spaces = pgTable(
  'pages_blocks_featured_spaces',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    title: varchar('title').default('Featured Spaces'),
    viewAllText: varchar('view_all_text').default('View All Spaces'),
    viewAllHref: varchar('view_all_href').default('/leasing'),
    bottomButtonLabel: varchar('bottom_button_label').default('VIEW ALL AVAILABLE SPACES'),
    bottomButtonHref: varchar('bottom_button_href').default('/leasing'),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('pages_blocks_featured_spaces_order_idx').on(columns._order),
    index('pages_blocks_featured_spaces_parent_id_idx').on(columns._parentID),
    index('pages_blocks_featured_spaces_path_idx').on(columns._path),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [pages.id],
      name: 'pages_blocks_featured_spaces_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const pages_blocks_stats_section_stats = pgTable(
  'pages_blocks_stats_section_stats',
  {
    _order: integer('_order').notNull(),
    _parentID: varchar('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    value: varchar('value'),
  },
  (columns) => [
    index('pages_blocks_stats_section_stats_order_idx').on(columns._order),
    index('pages_blocks_stats_section_stats_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [pages_blocks_stats_section.id],
      name: 'pages_blocks_stats_section_stats_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const pages_blocks_stats_section = pgTable(
  'pages_blocks_stats_section',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    title: varchar('title').default('A New Standard for Mixed-Use Living'),
    description: varchar('description'),
    primaryImage: integer('primary_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    secondaryImage: integer('secondary_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    estBadge: varchar('est_badge').default('Est. 2024'),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('pages_blocks_stats_section_order_idx').on(columns._order),
    index('pages_blocks_stats_section_parent_id_idx').on(columns._parentID),
    index('pages_blocks_stats_section_path_idx').on(columns._path),
    index('pages_blocks_stats_section_primary_image_idx').on(columns.primaryImage),
    index('pages_blocks_stats_section_secondary_image_idx').on(columns.secondaryImage),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [pages.id],
      name: 'pages_blocks_stats_section_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const pages_blocks_final_c_t_a = pgTable(
  'pages_blocks_final_c_t_a',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    title: varchar('title').default('Find Your Perfect Space at Oasis District'),
    backgroundImage: integer('background_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    primaryButtonLabel: varchar('primary_button_label').default('VIEW AVAILABLE SPACES'),
    primaryButtonHref: varchar('primary_button_href').default('/leasing'),
    secondaryButtonLabel: varchar('secondary_button_label').default('CONTACT SALES'),
    secondaryButtonHref: varchar('secondary_button_href').default('/contact'),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('pages_blocks_final_c_t_a_order_idx').on(columns._order),
    index('pages_blocks_final_c_t_a_parent_id_idx').on(columns._parentID),
    index('pages_blocks_final_c_t_a_path_idx').on(columns._path),
    index('pages_blocks_final_c_t_a_background_image_idx').on(columns.backgroundImage),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [pages.id],
      name: 'pages_blocks_final_c_t_a_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const pages = pgTable(
  'pages',
  {
    id: serial('id').primaryKey(),
    title: varchar('title'),
    slug: varchar('slug'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    _status: enum_pages_status('_status').default('draft'),
  },
  (columns) => [
    uniqueIndex('pages_slug_idx').on(columns.slug),
    index('pages_updated_at_idx').on(columns.updatedAt),
    index('pages_created_at_idx').on(columns.createdAt),
    index('pages__status_idx').on(columns._status),
  ],
)

export const pages_rels = pgTable(
  'pages_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    categoriesID: integer('categories_id'),
  },
  (columns) => [
    index('pages_rels_order_idx').on(columns.order),
    index('pages_rels_parent_idx').on(columns.parent),
    index('pages_rels_path_idx').on(columns.path),
    index('pages_rels_categories_id_idx').on(columns.categoriesID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [pages.id],
      name: 'pages_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['categoriesID']],
      foreignColumns: [categories.id],
      name: 'pages_rels_categories_fk',
    }).onDelete('cascade'),
  ],
)

export const _pages_v_blocks_hero = pgTable(
  '_pages_v_blocks_hero',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: serial('id').primaryKey(),
    title: varchar('title'),
    subtitle: varchar('subtitle'),
    image: integer('image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    _uuid: varchar('_uuid'),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('_pages_v_blocks_hero_order_idx').on(columns._order),
    index('_pages_v_blocks_hero_parent_id_idx').on(columns._parentID),
    index('_pages_v_blocks_hero_path_idx').on(columns._path),
    index('_pages_v_blocks_hero_image_idx').on(columns.image),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [_pages_v.id],
      name: '_pages_v_blocks_hero_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const _pages_v_blocks_inventory_grid = pgTable(
  '_pages_v_blocks_inventory_grid',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: serial('id').primaryKey(),
    title: varchar('title'),
    _uuid: varchar('_uuid'),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('_pages_v_blocks_inventory_grid_order_idx').on(columns._order),
    index('_pages_v_blocks_inventory_grid_parent_id_idx').on(columns._parentID),
    index('_pages_v_blocks_inventory_grid_path_idx').on(columns._path),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [_pages_v.id],
      name: '_pages_v_blocks_inventory_grid_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const _pages_v_blocks_content = pgTable(
  '_pages_v_blocks_content',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: serial('id').primaryKey(),
    richText: jsonb('rich_text'),
    _uuid: varchar('_uuid'),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('_pages_v_blocks_content_order_idx').on(columns._order),
    index('_pages_v_blocks_content_parent_id_idx').on(columns._parentID),
    index('_pages_v_blocks_content_path_idx').on(columns._path),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [_pages_v.id],
      name: '_pages_v_blocks_content_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const _pages_v_blocks_cowork_hero_amenities = pgTable(
  '_pages_v_blocks_cowork_hero_amenities',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: serial('id').primaryKey(),
    icon: enum__pages_v_blocks_cowork_hero_amenities_icon('icon'),
    label: varchar('label'),
    _uuid: varchar('_uuid'),
  },
  (columns) => [
    index('_pages_v_blocks_cowork_hero_amenities_order_idx').on(columns._order),
    index('_pages_v_blocks_cowork_hero_amenities_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [_pages_v_blocks_cowork_hero.id],
      name: '_pages_v_blocks_cowork_hero_amenities_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const _pages_v_blocks_cowork_hero = pgTable(
  '_pages_v_blocks_cowork_hero',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: serial('id').primaryKey(),
    overTitle: varchar('over_title'),
    title: varchar('title'),
    description: varchar('description'),
    backgroundImage: integer('background_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    _uuid: varchar('_uuid'),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('_pages_v_blocks_cowork_hero_order_idx').on(columns._order),
    index('_pages_v_blocks_cowork_hero_parent_id_idx').on(columns._parentID),
    index('_pages_v_blocks_cowork_hero_path_idx').on(columns._path),
    index('_pages_v_blocks_cowork_hero_background_image_idx').on(columns.backgroundImage),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [_pages_v.id],
      name: '_pages_v_blocks_cowork_hero_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const _pages_v_blocks_pricing_cards_plans_features = pgTable(
  '_pages_v_blocks_pricing_cards_plans_features',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: serial('id').primaryKey(),
    feature: varchar('feature'),
    _uuid: varchar('_uuid'),
  },
  (columns) => [
    index('_pages_v_blocks_pricing_cards_plans_features_order_idx').on(columns._order),
    index('_pages_v_blocks_pricing_cards_plans_features_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [_pages_v_blocks_pricing_cards_plans.id],
      name: '_pages_v_blocks_pricing_cards_plans_features_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const _pages_v_blocks_pricing_cards_plans = pgTable(
  '_pages_v_blocks_pricing_cards_plans',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: serial('id').primaryKey(),
    name: varchar('name'),
    price: numeric('price', { mode: 'number' }),
    frequency: varchar('frequency').default('/month'),
    isFeatured: boolean('is_featured').default(false),
    _uuid: varchar('_uuid'),
  },
  (columns) => [
    index('_pages_v_blocks_pricing_cards_plans_order_idx').on(columns._order),
    index('_pages_v_blocks_pricing_cards_plans_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [_pages_v_blocks_pricing_cards.id],
      name: '_pages_v_blocks_pricing_cards_plans_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const _pages_v_blocks_pricing_cards = pgTable(
  '_pages_v_blocks_pricing_cards',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: serial('id').primaryKey(),
    overTitle: varchar('over_title'),
    title: varchar('title'),
    _uuid: varchar('_uuid'),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('_pages_v_blocks_pricing_cards_order_idx').on(columns._order),
    index('_pages_v_blocks_pricing_cards_parent_id_idx').on(columns._parentID),
    index('_pages_v_blocks_pricing_cards_path_idx').on(columns._path),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [_pages_v.id],
      name: '_pages_v_blocks_pricing_cards_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const _pages_v_blocks_split_lead_section = pgTable(
  '_pages_v_blocks_split_lead_section',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: serial('id').primaryKey(),
    image: integer('image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    overTitle: varchar('over_title'),
    title: varchar('title'),
    description: varchar('description'),
    formTitle: varchar('form_title').default('Request Information'),
    formDescription: varchar('form_description').default(
      'Tell us what you need and our leasing team will contact you shortly.',
    ),
    _uuid: varchar('_uuid'),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('_pages_v_blocks_split_lead_section_order_idx').on(columns._order),
    index('_pages_v_blocks_split_lead_section_parent_id_idx').on(columns._parentID),
    index('_pages_v_blocks_split_lead_section_path_idx').on(columns._path),
    index('_pages_v_blocks_split_lead_section_image_idx').on(columns.image),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [_pages_v.id],
      name: '_pages_v_blocks_split_lead_section_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const _pages_v_blocks_home_hero = pgTable(
  '_pages_v_blocks_home_hero',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: serial('id').primaryKey(),
    announcementText: varchar('announcement_text').default('Now Leasing'),
    title: varchar('title'),
    subtitle: varchar('subtitle'),
    backgroundImage: integer('background_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    primaryButtonLabel: varchar('primary_button_label').default('VIEW AVAILABLE SPACES'),
    primaryButtonHref: varchar('primary_button_href').default('/leasing'),
    secondaryButtonLabel: varchar('secondary_button_label').default('OUR STORY'),
    secondaryButtonHref: varchar('secondary_button_href').default('/home'),
    _uuid: varchar('_uuid'),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('_pages_v_blocks_home_hero_order_idx').on(columns._order),
    index('_pages_v_blocks_home_hero_parent_id_idx').on(columns._parentID),
    index('_pages_v_blocks_home_hero_path_idx').on(columns._path),
    index('_pages_v_blocks_home_hero_background_image_idx').on(columns.backgroundImage),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [_pages_v.id],
      name: '_pages_v_blocks_home_hero_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const _pages_v_blocks_services_grid_items = pgTable(
  '_pages_v_blocks_services_grid_items',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: serial('id').primaryKey(),
    title: varchar('title'),
    image: integer('image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    href: varchar('href'),
    _uuid: varchar('_uuid'),
  },
  (columns) => [
    index('_pages_v_blocks_services_grid_items_order_idx').on(columns._order),
    index('_pages_v_blocks_services_grid_items_parent_id_idx').on(columns._parentID),
    index('_pages_v_blocks_services_grid_items_image_idx').on(columns.image),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [_pages_v_blocks_services_grid.id],
      name: '_pages_v_blocks_services_grid_items_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const _pages_v_blocks_services_grid = pgTable(
  '_pages_v_blocks_services_grid',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: serial('id').primaryKey(),
    title: varchar('title').default('Everything You Need, All in One Place'),
    description: varchar('description'),
    _uuid: varchar('_uuid'),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('_pages_v_blocks_services_grid_order_idx').on(columns._order),
    index('_pages_v_blocks_services_grid_parent_id_idx').on(columns._parentID),
    index('_pages_v_blocks_services_grid_path_idx').on(columns._path),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [_pages_v.id],
      name: '_pages_v_blocks_services_grid_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const _pages_v_blocks_featured_spaces = pgTable(
  '_pages_v_blocks_featured_spaces',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: serial('id').primaryKey(),
    title: varchar('title').default('Featured Spaces'),
    viewAllText: varchar('view_all_text').default('View All Spaces'),
    viewAllHref: varchar('view_all_href').default('/leasing'),
    bottomButtonLabel: varchar('bottom_button_label').default('VIEW ALL AVAILABLE SPACES'),
    bottomButtonHref: varchar('bottom_button_href').default('/leasing'),
    _uuid: varchar('_uuid'),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('_pages_v_blocks_featured_spaces_order_idx').on(columns._order),
    index('_pages_v_blocks_featured_spaces_parent_id_idx').on(columns._parentID),
    index('_pages_v_blocks_featured_spaces_path_idx').on(columns._path),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [_pages_v.id],
      name: '_pages_v_blocks_featured_spaces_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const _pages_v_blocks_stats_section_stats = pgTable(
  '_pages_v_blocks_stats_section_stats',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: serial('id').primaryKey(),
    value: varchar('value'),
    _uuid: varchar('_uuid'),
  },
  (columns) => [
    index('_pages_v_blocks_stats_section_stats_order_idx').on(columns._order),
    index('_pages_v_blocks_stats_section_stats_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [_pages_v_blocks_stats_section.id],
      name: '_pages_v_blocks_stats_section_stats_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const _pages_v_blocks_stats_section = pgTable(
  '_pages_v_blocks_stats_section',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: serial('id').primaryKey(),
    title: varchar('title').default('A New Standard for Mixed-Use Living'),
    description: varchar('description'),
    primaryImage: integer('primary_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    secondaryImage: integer('secondary_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    estBadge: varchar('est_badge').default('Est. 2024'),
    _uuid: varchar('_uuid'),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('_pages_v_blocks_stats_section_order_idx').on(columns._order),
    index('_pages_v_blocks_stats_section_parent_id_idx').on(columns._parentID),
    index('_pages_v_blocks_stats_section_path_idx').on(columns._path),
    index('_pages_v_blocks_stats_section_primary_image_idx').on(columns.primaryImage),
    index('_pages_v_blocks_stats_section_secondary_image_idx').on(columns.secondaryImage),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [_pages_v.id],
      name: '_pages_v_blocks_stats_section_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const _pages_v_blocks_final_c_t_a = pgTable(
  '_pages_v_blocks_final_c_t_a',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: serial('id').primaryKey(),
    title: varchar('title').default('Find Your Perfect Space at Oasis District'),
    backgroundImage: integer('background_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    primaryButtonLabel: varchar('primary_button_label').default('VIEW AVAILABLE SPACES'),
    primaryButtonHref: varchar('primary_button_href').default('/leasing'),
    secondaryButtonLabel: varchar('secondary_button_label').default('CONTACT SALES'),
    secondaryButtonHref: varchar('secondary_button_href').default('/contact'),
    _uuid: varchar('_uuid'),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('_pages_v_blocks_final_c_t_a_order_idx').on(columns._order),
    index('_pages_v_blocks_final_c_t_a_parent_id_idx').on(columns._parentID),
    index('_pages_v_blocks_final_c_t_a_path_idx').on(columns._path),
    index('_pages_v_blocks_final_c_t_a_background_image_idx').on(columns.backgroundImage),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [_pages_v.id],
      name: '_pages_v_blocks_final_c_t_a_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const _pages_v = pgTable(
  '_pages_v',
  {
    id: serial('id').primaryKey(),
    parent: integer('parent_id').references(() => pages.id, {
      onDelete: 'set null',
    }),
    version_title: varchar('version_title'),
    version_slug: varchar('version_slug'),
    version_updatedAt: timestamp('version_updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version_createdAt: timestamp('version_created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version__status: enum__pages_v_version_status('version__status').default('draft'),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    latest: boolean('latest'),
  },
  (columns) => [
    index('_pages_v_parent_idx').on(columns.parent),
    index('_pages_v_version_version_slug_idx').on(columns.version_slug),
    index('_pages_v_version_version_updated_at_idx').on(columns.version_updatedAt),
    index('_pages_v_version_version_created_at_idx').on(columns.version_createdAt),
    index('_pages_v_version_version__status_idx').on(columns.version__status),
    index('_pages_v_created_at_idx').on(columns.createdAt),
    index('_pages_v_updated_at_idx').on(columns.updatedAt),
    index('_pages_v_latest_idx').on(columns.latest),
  ],
)

export const _pages_v_rels = pgTable(
  '_pages_v_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    categoriesID: integer('categories_id'),
  },
  (columns) => [
    index('_pages_v_rels_order_idx').on(columns.order),
    index('_pages_v_rels_parent_idx').on(columns.parent),
    index('_pages_v_rels_path_idx').on(columns.path),
    index('_pages_v_rels_categories_id_idx').on(columns.categoriesID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [_pages_v.id],
      name: '_pages_v_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['categoriesID']],
      foreignColumns: [categories.id],
      name: '_pages_v_rels_categories_fk',
    }).onDelete('cascade'),
  ],
)

export const leads = pgTable(
  'leads',
  {
    id: serial('id').primaryKey(),
    fullName: varchar('full_name').notNull(),
    email: varchar('email').notNull(),
    phone: varchar('phone'),
    company: varchar('company'),
    interest: enum_leads_interest('interest'),
    message: varchar('message'),
    sourcePage: varchar('source_page'),
    sourceMetadata: varchar('source_metadata'),
    formType: enum_leads_form_type('form_type'),
    status: enum_leads_status('status').default('new'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('leads_updated_at_idx').on(columns.updatedAt),
    index('leads_created_at_idx').on(columns.createdAt),
  ],
)

export const posts = pgTable(
  'posts',
  {
    id: serial('id').primaryKey(),
    title: varchar('title').notNull(),
    slug: varchar('slug').notNull(),
    excerpt: varchar('excerpt').notNull(),
    categoryTag: enum_posts_category_tag('category_tag').notNull(),
    featuredImage: integer('featured_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    publishedAt: timestamp('published_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }).notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('posts_slug_idx').on(columns.slug),
    index('posts_featured_image_idx').on(columns.featuredImage),
    index('posts_updated_at_idx').on(columns.updatedAt),
    index('posts_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_kv = pgTable(
  'payload_kv',
  {
    id: serial('id').primaryKey(),
    key: varchar('key').notNull(),
    data: jsonb('data').notNull(),
  },
  (columns) => [uniqueIndex('payload_kv_key_idx').on(columns.key)],
)

export const payload_locked_documents = pgTable(
  'payload_locked_documents',
  {
    id: serial('id').primaryKey(),
    globalSlug: varchar('global_slug'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_locked_documents_global_slug_idx').on(columns.globalSlug),
    index('payload_locked_documents_updated_at_idx').on(columns.updatedAt),
    index('payload_locked_documents_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_locked_documents_rels = pgTable(
  'payload_locked_documents_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    usersID: integer('users_id'),
    mediaID: integer('media_id'),
    categoriesID: integer('categories_id'),
    unitsID: integer('units_id'),
    directoryID: integer('directory_id'),
    pagesID: integer('pages_id'),
    leadsID: integer('leads_id'),
    postsID: integer('posts_id'),
  },
  (columns) => [
    index('payload_locked_documents_rels_order_idx').on(columns.order),
    index('payload_locked_documents_rels_parent_idx').on(columns.parent),
    index('payload_locked_documents_rels_path_idx').on(columns.path),
    index('payload_locked_documents_rels_users_id_idx').on(columns.usersID),
    index('payload_locked_documents_rels_media_id_idx').on(columns.mediaID),
    index('payload_locked_documents_rels_categories_id_idx').on(columns.categoriesID),
    index('payload_locked_documents_rels_units_id_idx').on(columns.unitsID),
    index('payload_locked_documents_rels_directory_id_idx').on(columns.directoryID),
    index('payload_locked_documents_rels_pages_id_idx').on(columns.pagesID),
    index('payload_locked_documents_rels_leads_id_idx').on(columns.leadsID),
    index('payload_locked_documents_rels_posts_id_idx').on(columns.postsID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_locked_documents.id],
      name: 'payload_locked_documents_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_locked_documents_rels_users_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['mediaID']],
      foreignColumns: [media.id],
      name: 'payload_locked_documents_rels_media_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['categoriesID']],
      foreignColumns: [categories.id],
      name: 'payload_locked_documents_rels_categories_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['unitsID']],
      foreignColumns: [units.id],
      name: 'payload_locked_documents_rels_units_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['directoryID']],
      foreignColumns: [directory.id],
      name: 'payload_locked_documents_rels_directory_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['pagesID']],
      foreignColumns: [pages.id],
      name: 'payload_locked_documents_rels_pages_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['leadsID']],
      foreignColumns: [leads.id],
      name: 'payload_locked_documents_rels_leads_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['postsID']],
      foreignColumns: [posts.id],
      name: 'payload_locked_documents_rels_posts_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_preferences = pgTable(
  'payload_preferences',
  {
    id: serial('id').primaryKey(),
    key: varchar('key'),
    value: jsonb('value'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_preferences_key_idx').on(columns.key),
    index('payload_preferences_updated_at_idx').on(columns.updatedAt),
    index('payload_preferences_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_preferences_rels = pgTable(
  'payload_preferences_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    usersID: integer('users_id'),
  },
  (columns) => [
    index('payload_preferences_rels_order_idx').on(columns.order),
    index('payload_preferences_rels_parent_idx').on(columns.parent),
    index('payload_preferences_rels_path_idx').on(columns.path),
    index('payload_preferences_rels_users_id_idx').on(columns.usersID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_preferences.id],
      name: 'payload_preferences_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_preferences_rels_users_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_migrations = pgTable(
  'payload_migrations',
  {
    id: serial('id').primaryKey(),
    name: varchar('name'),
    batch: numeric('batch', { mode: 'number' }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_migrations_updated_at_idx').on(columns.updatedAt),
    index('payload_migrations_created_at_idx').on(columns.createdAt),
  ],
)

export const relations_users_sessions = relations(users_sessions, ({ one }) => ({
  _parentID: one(users, {
    fields: [users_sessions._parentID],
    references: [users.id],
    relationName: 'sessions',
  }),
}))
export const relations_users = relations(users, ({ many }) => ({
  sessions: many(users_sessions, {
    relationName: 'sessions',
  }),
}))
export const relations_media = relations(media, () => ({}))
export const relations_categories_marketing_content_quick_specs = relations(
  categories_marketing_content_quick_specs,
  ({ one }) => ({
    _parentID: one(categories, {
      fields: [categories_marketing_content_quick_specs._parentID],
      references: [categories.id],
      relationName: 'marketingContent_quickSpecs',
    }),
  }),
)
export const relations_categories = relations(categories, ({ one, many }) => ({
  heroBackgroundImage: one(media, {
    fields: [categories.heroBackgroundImage],
    references: [media.id],
    relationName: 'heroBackgroundImage',
  }),
  marketingContent_quickSpecs: many(categories_marketing_content_quick_specs, {
    relationName: 'marketingContent_quickSpecs',
  }),
}))
export const relations_units_features = relations(units_features, ({ one }) => ({
  _parentID: one(units, {
    fields: [units_features._parentID],
    references: [units.id],
    relationName: 'features',
  }),
}))
export const relations_units_rels = relations(units_rels, ({ one }) => ({
  parent: one(units, {
    fields: [units_rels.parent],
    references: [units.id],
    relationName: '_rels',
  }),
  mediaID: one(media, {
    fields: [units_rels.mediaID],
    references: [media.id],
    relationName: 'media',
  }),
}))
export const relations_units = relations(units, ({ one, many }) => ({
  type: one(categories, {
    fields: [units.type],
    references: [categories.id],
    relationName: 'type',
  }),
  floorPlan: one(media, {
    fields: [units.floorPlan],
    references: [media.id],
    relationName: 'floorPlan',
  }),
  features: many(units_features, {
    relationName: 'features',
  }),
  _rels: many(units_rels, {
    relationName: '_rels',
  }),
}))
export const relations_directory = relations(directory, ({ one }) => ({
  logo: one(media, {
    fields: [directory.logo],
    references: [media.id],
    relationName: 'logo',
  }),
  unit: one(units, {
    fields: [directory.unit],
    references: [units.id],
    relationName: 'unit',
  }),
  category: one(categories, {
    fields: [directory.category],
    references: [categories.id],
    relationName: 'category',
  }),
}))
export const relations_pages_blocks_hero = relations(pages_blocks_hero, ({ one }) => ({
  _parentID: one(pages, {
    fields: [pages_blocks_hero._parentID],
    references: [pages.id],
    relationName: '_blocks_hero',
  }),
  image: one(media, {
    fields: [pages_blocks_hero.image],
    references: [media.id],
    relationName: 'image',
  }),
}))
export const relations_pages_blocks_inventory_grid = relations(
  pages_blocks_inventory_grid,
  ({ one }) => ({
    _parentID: one(pages, {
      fields: [pages_blocks_inventory_grid._parentID],
      references: [pages.id],
      relationName: '_blocks_inventoryGrid',
    }),
  }),
)
export const relations_pages_blocks_content = relations(pages_blocks_content, ({ one }) => ({
  _parentID: one(pages, {
    fields: [pages_blocks_content._parentID],
    references: [pages.id],
    relationName: '_blocks_content',
  }),
}))
export const relations_pages_blocks_cowork_hero_amenities = relations(
  pages_blocks_cowork_hero_amenities,
  ({ one }) => ({
    _parentID: one(pages_blocks_cowork_hero, {
      fields: [pages_blocks_cowork_hero_amenities._parentID],
      references: [pages_blocks_cowork_hero.id],
      relationName: 'amenities',
    }),
  }),
)
export const relations_pages_blocks_cowork_hero = relations(
  pages_blocks_cowork_hero,
  ({ one, many }) => ({
    _parentID: one(pages, {
      fields: [pages_blocks_cowork_hero._parentID],
      references: [pages.id],
      relationName: '_blocks_coworkHero',
    }),
    backgroundImage: one(media, {
      fields: [pages_blocks_cowork_hero.backgroundImage],
      references: [media.id],
      relationName: 'backgroundImage',
    }),
    amenities: many(pages_blocks_cowork_hero_amenities, {
      relationName: 'amenities',
    }),
  }),
)
export const relations_pages_blocks_pricing_cards_plans_features = relations(
  pages_blocks_pricing_cards_plans_features,
  ({ one }) => ({
    _parentID: one(pages_blocks_pricing_cards_plans, {
      fields: [pages_blocks_pricing_cards_plans_features._parentID],
      references: [pages_blocks_pricing_cards_plans.id],
      relationName: 'features',
    }),
  }),
)
export const relations_pages_blocks_pricing_cards_plans = relations(
  pages_blocks_pricing_cards_plans,
  ({ one, many }) => ({
    _parentID: one(pages_blocks_pricing_cards, {
      fields: [pages_blocks_pricing_cards_plans._parentID],
      references: [pages_blocks_pricing_cards.id],
      relationName: 'plans',
    }),
    features: many(pages_blocks_pricing_cards_plans_features, {
      relationName: 'features',
    }),
  }),
)
export const relations_pages_blocks_pricing_cards = relations(
  pages_blocks_pricing_cards,
  ({ one, many }) => ({
    _parentID: one(pages, {
      fields: [pages_blocks_pricing_cards._parentID],
      references: [pages.id],
      relationName: '_blocks_pricingCards',
    }),
    plans: many(pages_blocks_pricing_cards_plans, {
      relationName: 'plans',
    }),
  }),
)
export const relations_pages_blocks_split_lead_section = relations(
  pages_blocks_split_lead_section,
  ({ one }) => ({
    _parentID: one(pages, {
      fields: [pages_blocks_split_lead_section._parentID],
      references: [pages.id],
      relationName: '_blocks_splitLeadSection',
    }),
    image: one(media, {
      fields: [pages_blocks_split_lead_section.image],
      references: [media.id],
      relationName: 'image',
    }),
  }),
)
export const relations_pages_blocks_home_hero = relations(pages_blocks_home_hero, ({ one }) => ({
  _parentID: one(pages, {
    fields: [pages_blocks_home_hero._parentID],
    references: [pages.id],
    relationName: '_blocks_homeHero',
  }),
  backgroundImage: one(media, {
    fields: [pages_blocks_home_hero.backgroundImage],
    references: [media.id],
    relationName: 'backgroundImage',
  }),
}))
export const relations_pages_blocks_services_grid_items = relations(
  pages_blocks_services_grid_items,
  ({ one }) => ({
    _parentID: one(pages_blocks_services_grid, {
      fields: [pages_blocks_services_grid_items._parentID],
      references: [pages_blocks_services_grid.id],
      relationName: 'items',
    }),
    image: one(media, {
      fields: [pages_blocks_services_grid_items.image],
      references: [media.id],
      relationName: 'image',
    }),
  }),
)
export const relations_pages_blocks_services_grid = relations(
  pages_blocks_services_grid,
  ({ one, many }) => ({
    _parentID: one(pages, {
      fields: [pages_blocks_services_grid._parentID],
      references: [pages.id],
      relationName: '_blocks_servicesGrid',
    }),
    items: many(pages_blocks_services_grid_items, {
      relationName: 'items',
    }),
  }),
)
export const relations_pages_blocks_featured_spaces = relations(
  pages_blocks_featured_spaces,
  ({ one }) => ({
    _parentID: one(pages, {
      fields: [pages_blocks_featured_spaces._parentID],
      references: [pages.id],
      relationName: '_blocks_featuredSpaces',
    }),
  }),
)
export const relations_pages_blocks_stats_section_stats = relations(
  pages_blocks_stats_section_stats,
  ({ one }) => ({
    _parentID: one(pages_blocks_stats_section, {
      fields: [pages_blocks_stats_section_stats._parentID],
      references: [pages_blocks_stats_section.id],
      relationName: 'stats',
    }),
  }),
)
export const relations_pages_blocks_stats_section = relations(
  pages_blocks_stats_section,
  ({ one, many }) => ({
    _parentID: one(pages, {
      fields: [pages_blocks_stats_section._parentID],
      references: [pages.id],
      relationName: '_blocks_statsSection',
    }),
    primaryImage: one(media, {
      fields: [pages_blocks_stats_section.primaryImage],
      references: [media.id],
      relationName: 'primaryImage',
    }),
    secondaryImage: one(media, {
      fields: [pages_blocks_stats_section.secondaryImage],
      references: [media.id],
      relationName: 'secondaryImage',
    }),
    stats: many(pages_blocks_stats_section_stats, {
      relationName: 'stats',
    }),
  }),
)
export const relations_pages_blocks_final_c_t_a = relations(
  pages_blocks_final_c_t_a,
  ({ one }) => ({
    _parentID: one(pages, {
      fields: [pages_blocks_final_c_t_a._parentID],
      references: [pages.id],
      relationName: '_blocks_finalCTA',
    }),
    backgroundImage: one(media, {
      fields: [pages_blocks_final_c_t_a.backgroundImage],
      references: [media.id],
      relationName: 'backgroundImage',
    }),
  }),
)
export const relations_pages_rels = relations(pages_rels, ({ one }) => ({
  parent: one(pages, {
    fields: [pages_rels.parent],
    references: [pages.id],
    relationName: '_rels',
  }),
  categoriesID: one(categories, {
    fields: [pages_rels.categoriesID],
    references: [categories.id],
    relationName: 'categories',
  }),
}))
export const relations_pages = relations(pages, ({ many }) => ({
  _blocks_hero: many(pages_blocks_hero, {
    relationName: '_blocks_hero',
  }),
  _blocks_inventoryGrid: many(pages_blocks_inventory_grid, {
    relationName: '_blocks_inventoryGrid',
  }),
  _blocks_content: many(pages_blocks_content, {
    relationName: '_blocks_content',
  }),
  _blocks_coworkHero: many(pages_blocks_cowork_hero, {
    relationName: '_blocks_coworkHero',
  }),
  _blocks_pricingCards: many(pages_blocks_pricing_cards, {
    relationName: '_blocks_pricingCards',
  }),
  _blocks_splitLeadSection: many(pages_blocks_split_lead_section, {
    relationName: '_blocks_splitLeadSection',
  }),
  _blocks_homeHero: many(pages_blocks_home_hero, {
    relationName: '_blocks_homeHero',
  }),
  _blocks_servicesGrid: many(pages_blocks_services_grid, {
    relationName: '_blocks_servicesGrid',
  }),
  _blocks_featuredSpaces: many(pages_blocks_featured_spaces, {
    relationName: '_blocks_featuredSpaces',
  }),
  _blocks_statsSection: many(pages_blocks_stats_section, {
    relationName: '_blocks_statsSection',
  }),
  _blocks_finalCTA: many(pages_blocks_final_c_t_a, {
    relationName: '_blocks_finalCTA',
  }),
  _rels: many(pages_rels, {
    relationName: '_rels',
  }),
}))
export const relations__pages_v_blocks_hero = relations(_pages_v_blocks_hero, ({ one }) => ({
  _parentID: one(_pages_v, {
    fields: [_pages_v_blocks_hero._parentID],
    references: [_pages_v.id],
    relationName: '_blocks_hero',
  }),
  image: one(media, {
    fields: [_pages_v_blocks_hero.image],
    references: [media.id],
    relationName: 'image',
  }),
}))
export const relations__pages_v_blocks_inventory_grid = relations(
  _pages_v_blocks_inventory_grid,
  ({ one }) => ({
    _parentID: one(_pages_v, {
      fields: [_pages_v_blocks_inventory_grid._parentID],
      references: [_pages_v.id],
      relationName: '_blocks_inventoryGrid',
    }),
  }),
)
export const relations__pages_v_blocks_content = relations(_pages_v_blocks_content, ({ one }) => ({
  _parentID: one(_pages_v, {
    fields: [_pages_v_blocks_content._parentID],
    references: [_pages_v.id],
    relationName: '_blocks_content',
  }),
}))
export const relations__pages_v_blocks_cowork_hero_amenities = relations(
  _pages_v_blocks_cowork_hero_amenities,
  ({ one }) => ({
    _parentID: one(_pages_v_blocks_cowork_hero, {
      fields: [_pages_v_blocks_cowork_hero_amenities._parentID],
      references: [_pages_v_blocks_cowork_hero.id],
      relationName: 'amenities',
    }),
  }),
)
export const relations__pages_v_blocks_cowork_hero = relations(
  _pages_v_blocks_cowork_hero,
  ({ one, many }) => ({
    _parentID: one(_pages_v, {
      fields: [_pages_v_blocks_cowork_hero._parentID],
      references: [_pages_v.id],
      relationName: '_blocks_coworkHero',
    }),
    backgroundImage: one(media, {
      fields: [_pages_v_blocks_cowork_hero.backgroundImage],
      references: [media.id],
      relationName: 'backgroundImage',
    }),
    amenities: many(_pages_v_blocks_cowork_hero_amenities, {
      relationName: 'amenities',
    }),
  }),
)
export const relations__pages_v_blocks_pricing_cards_plans_features = relations(
  _pages_v_blocks_pricing_cards_plans_features,
  ({ one }) => ({
    _parentID: one(_pages_v_blocks_pricing_cards_plans, {
      fields: [_pages_v_blocks_pricing_cards_plans_features._parentID],
      references: [_pages_v_blocks_pricing_cards_plans.id],
      relationName: 'features',
    }),
  }),
)
export const relations__pages_v_blocks_pricing_cards_plans = relations(
  _pages_v_blocks_pricing_cards_plans,
  ({ one, many }) => ({
    _parentID: one(_pages_v_blocks_pricing_cards, {
      fields: [_pages_v_blocks_pricing_cards_plans._parentID],
      references: [_pages_v_blocks_pricing_cards.id],
      relationName: 'plans',
    }),
    features: many(_pages_v_blocks_pricing_cards_plans_features, {
      relationName: 'features',
    }),
  }),
)
export const relations__pages_v_blocks_pricing_cards = relations(
  _pages_v_blocks_pricing_cards,
  ({ one, many }) => ({
    _parentID: one(_pages_v, {
      fields: [_pages_v_blocks_pricing_cards._parentID],
      references: [_pages_v.id],
      relationName: '_blocks_pricingCards',
    }),
    plans: many(_pages_v_blocks_pricing_cards_plans, {
      relationName: 'plans',
    }),
  }),
)
export const relations__pages_v_blocks_split_lead_section = relations(
  _pages_v_blocks_split_lead_section,
  ({ one }) => ({
    _parentID: one(_pages_v, {
      fields: [_pages_v_blocks_split_lead_section._parentID],
      references: [_pages_v.id],
      relationName: '_blocks_splitLeadSection',
    }),
    image: one(media, {
      fields: [_pages_v_blocks_split_lead_section.image],
      references: [media.id],
      relationName: 'image',
    }),
  }),
)
export const relations__pages_v_blocks_home_hero = relations(
  _pages_v_blocks_home_hero,
  ({ one }) => ({
    _parentID: one(_pages_v, {
      fields: [_pages_v_blocks_home_hero._parentID],
      references: [_pages_v.id],
      relationName: '_blocks_homeHero',
    }),
    backgroundImage: one(media, {
      fields: [_pages_v_blocks_home_hero.backgroundImage],
      references: [media.id],
      relationName: 'backgroundImage',
    }),
  }),
)
export const relations__pages_v_blocks_services_grid_items = relations(
  _pages_v_blocks_services_grid_items,
  ({ one }) => ({
    _parentID: one(_pages_v_blocks_services_grid, {
      fields: [_pages_v_blocks_services_grid_items._parentID],
      references: [_pages_v_blocks_services_grid.id],
      relationName: 'items',
    }),
    image: one(media, {
      fields: [_pages_v_blocks_services_grid_items.image],
      references: [media.id],
      relationName: 'image',
    }),
  }),
)
export const relations__pages_v_blocks_services_grid = relations(
  _pages_v_blocks_services_grid,
  ({ one, many }) => ({
    _parentID: one(_pages_v, {
      fields: [_pages_v_blocks_services_grid._parentID],
      references: [_pages_v.id],
      relationName: '_blocks_servicesGrid',
    }),
    items: many(_pages_v_blocks_services_grid_items, {
      relationName: 'items',
    }),
  }),
)
export const relations__pages_v_blocks_featured_spaces = relations(
  _pages_v_blocks_featured_spaces,
  ({ one }) => ({
    _parentID: one(_pages_v, {
      fields: [_pages_v_blocks_featured_spaces._parentID],
      references: [_pages_v.id],
      relationName: '_blocks_featuredSpaces',
    }),
  }),
)
export const relations__pages_v_blocks_stats_section_stats = relations(
  _pages_v_blocks_stats_section_stats,
  ({ one }) => ({
    _parentID: one(_pages_v_blocks_stats_section, {
      fields: [_pages_v_blocks_stats_section_stats._parentID],
      references: [_pages_v_blocks_stats_section.id],
      relationName: 'stats',
    }),
  }),
)
export const relations__pages_v_blocks_stats_section = relations(
  _pages_v_blocks_stats_section,
  ({ one, many }) => ({
    _parentID: one(_pages_v, {
      fields: [_pages_v_blocks_stats_section._parentID],
      references: [_pages_v.id],
      relationName: '_blocks_statsSection',
    }),
    primaryImage: one(media, {
      fields: [_pages_v_blocks_stats_section.primaryImage],
      references: [media.id],
      relationName: 'primaryImage',
    }),
    secondaryImage: one(media, {
      fields: [_pages_v_blocks_stats_section.secondaryImage],
      references: [media.id],
      relationName: 'secondaryImage',
    }),
    stats: many(_pages_v_blocks_stats_section_stats, {
      relationName: 'stats',
    }),
  }),
)
export const relations__pages_v_blocks_final_c_t_a = relations(
  _pages_v_blocks_final_c_t_a,
  ({ one }) => ({
    _parentID: one(_pages_v, {
      fields: [_pages_v_blocks_final_c_t_a._parentID],
      references: [_pages_v.id],
      relationName: '_blocks_finalCTA',
    }),
    backgroundImage: one(media, {
      fields: [_pages_v_blocks_final_c_t_a.backgroundImage],
      references: [media.id],
      relationName: 'backgroundImage',
    }),
  }),
)
export const relations__pages_v_rels = relations(_pages_v_rels, ({ one }) => ({
  parent: one(_pages_v, {
    fields: [_pages_v_rels.parent],
    references: [_pages_v.id],
    relationName: '_rels',
  }),
  categoriesID: one(categories, {
    fields: [_pages_v_rels.categoriesID],
    references: [categories.id],
    relationName: 'categories',
  }),
}))
export const relations__pages_v = relations(_pages_v, ({ one, many }) => ({
  parent: one(pages, {
    fields: [_pages_v.parent],
    references: [pages.id],
    relationName: 'parent',
  }),
  _blocks_hero: many(_pages_v_blocks_hero, {
    relationName: '_blocks_hero',
  }),
  _blocks_inventoryGrid: many(_pages_v_blocks_inventory_grid, {
    relationName: '_blocks_inventoryGrid',
  }),
  _blocks_content: many(_pages_v_blocks_content, {
    relationName: '_blocks_content',
  }),
  _blocks_coworkHero: many(_pages_v_blocks_cowork_hero, {
    relationName: '_blocks_coworkHero',
  }),
  _blocks_pricingCards: many(_pages_v_blocks_pricing_cards, {
    relationName: '_blocks_pricingCards',
  }),
  _blocks_splitLeadSection: many(_pages_v_blocks_split_lead_section, {
    relationName: '_blocks_splitLeadSection',
  }),
  _blocks_homeHero: many(_pages_v_blocks_home_hero, {
    relationName: '_blocks_homeHero',
  }),
  _blocks_servicesGrid: many(_pages_v_blocks_services_grid, {
    relationName: '_blocks_servicesGrid',
  }),
  _blocks_featuredSpaces: many(_pages_v_blocks_featured_spaces, {
    relationName: '_blocks_featuredSpaces',
  }),
  _blocks_statsSection: many(_pages_v_blocks_stats_section, {
    relationName: '_blocks_statsSection',
  }),
  _blocks_finalCTA: many(_pages_v_blocks_final_c_t_a, {
    relationName: '_blocks_finalCTA',
  }),
  _rels: many(_pages_v_rels, {
    relationName: '_rels',
  }),
}))
export const relations_leads = relations(leads, () => ({}))
export const relations_posts = relations(posts, ({ one }) => ({
  featuredImage: one(media, {
    fields: [posts.featuredImage],
    references: [media.id],
    relationName: 'featuredImage',
  }),
}))
export const relations_payload_kv = relations(payload_kv, () => ({}))
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: 'media',
    }),
    categoriesID: one(categories, {
      fields: [payload_locked_documents_rels.categoriesID],
      references: [categories.id],
      relationName: 'categories',
    }),
    unitsID: one(units, {
      fields: [payload_locked_documents_rels.unitsID],
      references: [units.id],
      relationName: 'units',
    }),
    directoryID: one(directory, {
      fields: [payload_locked_documents_rels.directoryID],
      references: [directory.id],
      relationName: 'directory',
    }),
    pagesID: one(pages, {
      fields: [payload_locked_documents_rels.pagesID],
      references: [pages.id],
      relationName: 'pages',
    }),
    leadsID: one(leads, {
      fields: [payload_locked_documents_rels.leadsID],
      references: [leads.id],
      relationName: 'leads',
    }),
    postsID: one(posts, {
      fields: [payload_locked_documents_rels.postsID],
      references: [posts.id],
      relationName: 'posts',
    }),
  }),
)
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: '_rels',
    }),
  }),
)
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
  }),
)
export const relations_payload_preferences = relations(payload_preferences, ({ many }) => ({
  _rels: many(payload_preferences_rels, {
    relationName: '_rels',
  }),
}))
export const relations_payload_migrations = relations(payload_migrations, () => ({}))

type DatabaseSchema = {
  enum_categories_marketing_content_quick_specs_icon: typeof enum_categories_marketing_content_quick_specs_icon
  enum_units_status: typeof enum_units_status
  enum_units_lease_type: typeof enum_units_lease_type
  enum_units_building: typeof enum_units_building
  enum_pages_blocks_cowork_hero_amenities_icon: typeof enum_pages_blocks_cowork_hero_amenities_icon
  enum_pages_status: typeof enum_pages_status
  enum__pages_v_blocks_cowork_hero_amenities_icon: typeof enum__pages_v_blocks_cowork_hero_amenities_icon
  enum__pages_v_version_status: typeof enum__pages_v_version_status
  enum_leads_interest: typeof enum_leads_interest
  enum_leads_form_type: typeof enum_leads_form_type
  enum_leads_status: typeof enum_leads_status
  enum_posts_category_tag: typeof enum_posts_category_tag
  users_sessions: typeof users_sessions
  users: typeof users
  media: typeof media
  categories_marketing_content_quick_specs: typeof categories_marketing_content_quick_specs
  categories: typeof categories
  units_features: typeof units_features
  units: typeof units
  units_rels: typeof units_rels
  directory: typeof directory
  pages_blocks_hero: typeof pages_blocks_hero
  pages_blocks_inventory_grid: typeof pages_blocks_inventory_grid
  pages_blocks_content: typeof pages_blocks_content
  pages_blocks_cowork_hero_amenities: typeof pages_blocks_cowork_hero_amenities
  pages_blocks_cowork_hero: typeof pages_blocks_cowork_hero
  pages_blocks_pricing_cards_plans_features: typeof pages_blocks_pricing_cards_plans_features
  pages_blocks_pricing_cards_plans: typeof pages_blocks_pricing_cards_plans
  pages_blocks_pricing_cards: typeof pages_blocks_pricing_cards
  pages_blocks_split_lead_section: typeof pages_blocks_split_lead_section
  pages_blocks_home_hero: typeof pages_blocks_home_hero
  pages_blocks_services_grid_items: typeof pages_blocks_services_grid_items
  pages_blocks_services_grid: typeof pages_blocks_services_grid
  pages_blocks_featured_spaces: typeof pages_blocks_featured_spaces
  pages_blocks_stats_section_stats: typeof pages_blocks_stats_section_stats
  pages_blocks_stats_section: typeof pages_blocks_stats_section
  pages_blocks_final_c_t_a: typeof pages_blocks_final_c_t_a
  pages: typeof pages
  pages_rels: typeof pages_rels
  _pages_v_blocks_hero: typeof _pages_v_blocks_hero
  _pages_v_blocks_inventory_grid: typeof _pages_v_blocks_inventory_grid
  _pages_v_blocks_content: typeof _pages_v_blocks_content
  _pages_v_blocks_cowork_hero_amenities: typeof _pages_v_blocks_cowork_hero_amenities
  _pages_v_blocks_cowork_hero: typeof _pages_v_blocks_cowork_hero
  _pages_v_blocks_pricing_cards_plans_features: typeof _pages_v_blocks_pricing_cards_plans_features
  _pages_v_blocks_pricing_cards_plans: typeof _pages_v_blocks_pricing_cards_plans
  _pages_v_blocks_pricing_cards: typeof _pages_v_blocks_pricing_cards
  _pages_v_blocks_split_lead_section: typeof _pages_v_blocks_split_lead_section
  _pages_v_blocks_home_hero: typeof _pages_v_blocks_home_hero
  _pages_v_blocks_services_grid_items: typeof _pages_v_blocks_services_grid_items
  _pages_v_blocks_services_grid: typeof _pages_v_blocks_services_grid
  _pages_v_blocks_featured_spaces: typeof _pages_v_blocks_featured_spaces
  _pages_v_blocks_stats_section_stats: typeof _pages_v_blocks_stats_section_stats
  _pages_v_blocks_stats_section: typeof _pages_v_blocks_stats_section
  _pages_v_blocks_final_c_t_a: typeof _pages_v_blocks_final_c_t_a
  _pages_v: typeof _pages_v
  _pages_v_rels: typeof _pages_v_rels
  leads: typeof leads
  posts: typeof posts
  payload_kv: typeof payload_kv
  payload_locked_documents: typeof payload_locked_documents
  payload_locked_documents_rels: typeof payload_locked_documents_rels
  payload_preferences: typeof payload_preferences
  payload_preferences_rels: typeof payload_preferences_rels
  payload_migrations: typeof payload_migrations
  relations_users_sessions: typeof relations_users_sessions
  relations_users: typeof relations_users
  relations_media: typeof relations_media
  relations_categories_marketing_content_quick_specs: typeof relations_categories_marketing_content_quick_specs
  relations_categories: typeof relations_categories
  relations_units_features: typeof relations_units_features
  relations_units_rels: typeof relations_units_rels
  relations_units: typeof relations_units
  relations_directory: typeof relations_directory
  relations_pages_blocks_hero: typeof relations_pages_blocks_hero
  relations_pages_blocks_inventory_grid: typeof relations_pages_blocks_inventory_grid
  relations_pages_blocks_content: typeof relations_pages_blocks_content
  relations_pages_blocks_cowork_hero_amenities: typeof relations_pages_blocks_cowork_hero_amenities
  relations_pages_blocks_cowork_hero: typeof relations_pages_blocks_cowork_hero
  relations_pages_blocks_pricing_cards_plans_features: typeof relations_pages_blocks_pricing_cards_plans_features
  relations_pages_blocks_pricing_cards_plans: typeof relations_pages_blocks_pricing_cards_plans
  relations_pages_blocks_pricing_cards: typeof relations_pages_blocks_pricing_cards
  relations_pages_blocks_split_lead_section: typeof relations_pages_blocks_split_lead_section
  relations_pages_blocks_home_hero: typeof relations_pages_blocks_home_hero
  relations_pages_blocks_services_grid_items: typeof relations_pages_blocks_services_grid_items
  relations_pages_blocks_services_grid: typeof relations_pages_blocks_services_grid
  relations_pages_blocks_featured_spaces: typeof relations_pages_blocks_featured_spaces
  relations_pages_blocks_stats_section_stats: typeof relations_pages_blocks_stats_section_stats
  relations_pages_blocks_stats_section: typeof relations_pages_blocks_stats_section
  relations_pages_blocks_final_c_t_a: typeof relations_pages_blocks_final_c_t_a
  relations_pages_rels: typeof relations_pages_rels
  relations_pages: typeof relations_pages
  relations__pages_v_blocks_hero: typeof relations__pages_v_blocks_hero
  relations__pages_v_blocks_inventory_grid: typeof relations__pages_v_blocks_inventory_grid
  relations__pages_v_blocks_content: typeof relations__pages_v_blocks_content
  relations__pages_v_blocks_cowork_hero_amenities: typeof relations__pages_v_blocks_cowork_hero_amenities
  relations__pages_v_blocks_cowork_hero: typeof relations__pages_v_blocks_cowork_hero
  relations__pages_v_blocks_pricing_cards_plans_features: typeof relations__pages_v_blocks_pricing_cards_plans_features
  relations__pages_v_blocks_pricing_cards_plans: typeof relations__pages_v_blocks_pricing_cards_plans
  relations__pages_v_blocks_pricing_cards: typeof relations__pages_v_blocks_pricing_cards
  relations__pages_v_blocks_split_lead_section: typeof relations__pages_v_blocks_split_lead_section
  relations__pages_v_blocks_home_hero: typeof relations__pages_v_blocks_home_hero
  relations__pages_v_blocks_services_grid_items: typeof relations__pages_v_blocks_services_grid_items
  relations__pages_v_blocks_services_grid: typeof relations__pages_v_blocks_services_grid
  relations__pages_v_blocks_featured_spaces: typeof relations__pages_v_blocks_featured_spaces
  relations__pages_v_blocks_stats_section_stats: typeof relations__pages_v_blocks_stats_section_stats
  relations__pages_v_blocks_stats_section: typeof relations__pages_v_blocks_stats_section
  relations__pages_v_blocks_final_c_t_a: typeof relations__pages_v_blocks_final_c_t_a
  relations__pages_v_rels: typeof relations__pages_v_rels
  relations__pages_v: typeof relations__pages_v
  relations_leads: typeof relations_leads
  relations_posts: typeof relations_posts
  relations_payload_kv: typeof relations_payload_kv
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels
  relations_payload_locked_documents: typeof relations_payload_locked_documents
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels
  relations_payload_preferences: typeof relations_payload_preferences
  relations_payload_migrations: typeof relations_payload_migrations
}

declare module '@payloadcms/db-postgres' {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema
  }
}
